title: Julie's Site
author: Julie Ham
email: julieham03@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The guide to the typical life of a typical teen about to enter pseudo-adult world.

# social links
twitter_username: julieham03 # DO NOT include the @ character, or else the build will fail!
github_username:  jjham1 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
